dist: trusty
sudo: false
language: go
go:
- 1.9

install: true

before_deploy:
- make packages

deploy:
  provider: releases
  api_key:
    secure: "Ei4H6JpMrH/wvKCXq9u4pbbcdlChwjCSZQjMMQ4SGxqJ/kcrTjdF5PKaFxbXJP9y2uJ4St/V1isCJOUcQiDm5dcjwQ5M7Y2FNwMduyOvzFP1SRtwNcTHf08hPn8qXHHd1z141wpmIGMHnXaDnO3IMV2slxwS8SfUH9FEHSQQiIjlNKRJAIqfTd8hLV0pp/emvvTevf7HnxwH4UpkDmRPjfzyexqXY7lgWb09qadH4Ua5E479WS7LiVTCSiL5aTLwCOQs/VFqoa1z6EvisCZX3XTHsMr3Vb2I9wmnXk8DENDK0z7KW9cV3wNNjAN8B/ZzJH8JawUaHc8H/4yV2A2R9+VmwThJkEObUsJDzsA6+v4N5uV1JLXSLnwA4+bHOMjkIwgnP8HtRAzdIPik4unnGetXeVSGuMhz/B0DK7DaMluaP8KgkvJZyh/H+kxh3uRV3/NjSAXdV/f1cIkwnN6DI1w5yn9MrmWmFmJoa8A7I8bphCNM/k2gPkZjaGcxCgVGvf93VLtbJ82Potn2Pu2l3n+yuFmU0qYTUBV4Hfbw/kBazYrHqNcPrbNYyl+LO6HVdTPEWBVJR+VzHyhImbPGwipOB4dfGe646DEqlQF6vBe7Rj6z008SNLtDzaMFFUg1fxE/prCwZu9OID2iGSGdPRyZUUAjtqE/MQJwNu/QT6Y="
  file:
  - build/terraform-provider-s3site_${TRAVIS_TAG}_darwin_amd64.tar.gz
  - build/terraform-provider-s3site_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
