dist: trusty
sudo: false
language: go
go:
- 1.9

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/terraform-provider-s3site_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/terraform-provider-s3site_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true