version: 2
jobs:
  build:
    docker:
      - image: golang:1.14.15
    working_directory: /terraform-provider-s3site
    steps:
      - checkout
      - run:
          name: Test
          command: |
            go test -mod=readonly -cover ./...
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=darwin GOARCH=386 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-darwin-386
            CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-darwin-amd64
            # CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-linux-386
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-linux-amd64
            # CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-linux-arm
            # CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-windows-386.exe
            # CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -mod=readonly -ldflags="-s -w" -a -o build/terraform-provider-s3site-windows-amd64.exe
      - run:
          name: Compute checksum of binaries
          command: |
            for binary in build/*; do
              sha256sum -b $binary > $binary.sha256
            done
      - persist_to_workspace:
          root: /terraform-provider-s3site
          paths:
            - build
  release:
    working_directory: /build
    docker:
      - image: golang:1.14.15
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Instal GHR
          command: |
            go get github.com/tcnksm/ghr
      - run:
          name: Publish release
          command: |
            ghr -t ${GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -draft ${CIRCLE_TAG} .

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          context: sonrai-context
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/